input {
    tcp {
        port => 5000
    }
}

filter {
    mutate {
        add_field => { "tag" => "Docker-Log" }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "docker-logs-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
}